<a href="https://colab.research.google.com/github/Moquiuti/NLP/blob/main/TF_IDF_com_N_Grams_para_an%C3%A1lise_de_sentimentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import nltk

nltk.download('rslp')

[nltk_data] Downloading package rslp to /root/nltk_data...
[nltk_data]   Unzipping stemmers/rslp.zip.

True

In [4]:
!pip install unidecode

Collecting unidecode
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 5.2 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.4.0

In [6]:
import pandas as pd
import nltk
from nltk import tokenize
from unidecode import unidecode

nltk.download('stopwords')
nltk.download('rslp')

df = pd.read_csv('dataset_avaliacoes.csv')

palavras_irrelevantes = nltk.corpus.stopwords.words('portuguese')

stopwords_sem_acento = [
    unidecode(palavra) for palavra in palavras_irrelevantes
]

token_pontuacao = tokenize.WordPunctTokenizer()
stemmer = nltk.RSLPStemmer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package rslp to /root/nltk_data...
[nltk_data]   Package rslp is already up-to-date!

In [7]:
from nltk import tokenize
import pandas as pd

stemmer = nltk.RSLPStemmer()
token_pontuacao = tokenize.WordPunctTokenizer()

frase_processada = []

df = pd.read_csv('dataset_avaliacoes.csv')
df.head()
for opiniao in df["avaliacao"]:
    palavras_texto = token_pontuacao.tokenize(opiniao)

    nova_frase = [
        stemmer.stem(palavra)
        for palavra in palavras_texto
        if palavra not in stopwords_sem_acento
    ]

    frase_processada.append(' '.join(nova_frase))

df["tratamento_5"] = frase_processada

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

frases = [
    "Comprei um produto ótimo",
    "Comprei um produto péssimo"
]

tfidf = TfidfVectorizer(lowercase=False, max_features=50)

caracteristicas = tfidf.fit_transform(frases)

pd.DataFrame(
    caracteristicas.todense(),
    columns=tfidf.get_feature_names_out()
)

    Comprei   produto   péssimo        um     ótimo
0  0.448321  0.448321  0.000000  0.448321  0.630099
1  0.448321  0.448321  0.630099  0.448321  0.000000

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

tfidf = TfidfVectorizer(lowercase=False, max_features=50)

tfidf_tratados = tfidf.fit_transform(df["tratamento_5"])

X_treino, X_teste, y_treino, y_teste = train_test_split(
    tfidf_tratados,
    df["sentimento"],
    random_state=4978
)

regressao_logistica = LogisticRegression(max_iter=1000)
regressao_logistica.fit(X_treino, y_treino)

acuracia_tfidf_tratados = regressao_logistica.score(X_teste, y_teste)

print(f"Acurácia do modelo: {acuracia_tfidf_tratados * 100:.2f} %")

Acurácia do modelo: 86.33 %

In [10]:
tfidf_50 = TfidfVectorizer(
    lowercase=False,
    max_features=50,
    ngram_range=(1, 2)
)

vetor_tfidf = tfidf_50.fit_transform(df["tratamento_5"])

X_treino, X_teste, y_treino, y_teste = train_test_split(
    vetor_tfidf,
    df["sentimento"],
    random_state=4978
)

regressao_logistica = LogisticRegression(max_iter=1000)
regressao_logistica.fit(X_treino, y_treino)

acuracia_tfidf_ngrams = regressao_logistica.score(X_teste, y_teste)

print(f"Acurácia do modelo com 50 features e ngrams: {acuracia_tfidf_ngrams * 100:.2f} %")

Acurácia do modelo com 50 features e ngrams: 86.33 %

In [11]:
tfidf_1000 = TfidfVectorizer(
    lowercase=False,
    max_features=1000,
    ngram_range=(1, 2)
)

vetor_tfidf_1000 = tfidf_1000.fit_transform(df["tratamento_5"])

X_treino, X_teste, y_treino, y_teste = train_test_split(
    vetor_tfidf_1000,
    df["sentimento"],
    random_state=4978
)

regressao_logistica = LogisticRegression(max_iter=1000)
regressao_logistica.fit(X_treino, y_treino)

acuracia_tfidf_ngrams_1000 = regressao_logistica.score(X_teste, y_teste)

print(f"Acurácia do modelo com 1000 features e ngrams: {acuracia_tfidf_ngrams_1000 * 100:.2f} %")

Acurácia do modelo com 1000 features e ngrams: 93.29 %

In [12]:
pesos = pd.DataFrame(
    regressao_logistica.coef_[0].T,
    index=tfidf_1000.get_feature_names_out(),
    columns=["peso"]
)

In [13]:
pesos.nlargest(50, "peso")

                  peso
ótim          7.369779
excel         7.032308
bom           5.343555
ador          4.607107
perfeit       4.546882
recom         4.402985
satisfeit     4.344612
gost          3.967776
rápid         3.666547
lind          3.471849
otim          3.263249
ame           3.181436
maravilh      3.172695
expect        2.965865
bem           2.711329
prát          2.641424
boa           2.630887
sup           2.594144
bast          2.570872
surpreend     2.509927
muit bom      2.436830
fácil         2.293108
exat          2.141067
top           2.108792
bonit         2.012454
conhec        2.002954
únic          1.991684
gost produt   1.973584
ótim produt   1.958404
só não        1.942705
parabém       1.909498
obrig         1.898764
facilit       1.873938
produt bom    1.820298
tud           1.819008
só            1.817782
amou          1.813632
ant praz      1.807637
pen           1.804171
ideal         1.767037
só ach        1.765180
necess        1.764968
melhor        1.741652
atend         1.716299
rap           1.686401
ant           1.666631
incr          1.614808
feliz         1.589888
produt excel  1.554994
ok            1.535599

In [14]:
pesos.nsmallest(50, "peso")

                  peso
não          -6.389915
não recom    -4.559716
ruim         -3.890948
péss         -3.723793
frac         -3.688440
receb        -3.465814
defeit       -3.179270
não gost     -2.891092
vei          -2.743940
horr         -2.682500
decepcion    -2.650660
devolv       -2.570621
produt não   -2.498637
frágil       -2.454879
dinh         -2.392647
quebr        -2.289410
solt         -2.270307
pag          -2.258150
não receb    -2.243189
não func     -2.241685
nao          -2.215689
pess         -2.200840
na           -2.098227
não cumpr    -2.037274
mê           -2.006773
devoluç      -1.982102
inferi       -1.975847
troc         -1.946105
regul        -1.923964
mes          -1.911721
lent         -1.897740
pi           -1.873788
porém        -1.860234
rasg         -1.847122
cancel       -1.846288
receb produt -1.828619
porc         -1.824347
baix qual    -1.823790
err          -1.815360
absurd       -1.814606
tent         -1.781827
insatisfeit  -1.774576
não val      -1.774381
mal          -1.771391
queim        -1.765126
mand         -1.756105
péss qual    -1.741327
baix         -1.736347
fal          -1.716634
ta           -1.683461